### ISSUE TITLE
SoftwareUpdate check flushes the cache

### ISSUE THREAD

**Issue by ecaya-hopper** [Macjutsu/super#119]
Recently we've seen an issue where users could basically disregard our prompts as the zero day kept being updated.

This can be reproduced if 
1. The current update has been found and cached
2. The user decides to dismiss our prompt for 6+ hours
3. Since the check has happened for longer than 6 hours, super double check with software update
### 4. The softwareupdate check loop fails ; either bypasses the timeout and lasts upwards of 2 hours, or fails immediately without even reporting "softwareupdate: Waiting for update list..."
6. super defaults to no update being available
7. super runs again the next day (deferralcheck is set to 86400 seconds), detects the patch again and sets a new zero day

However the softwareupdate process itself is working, an extension attribute we've set via Jamf reports the update correctly (and is ran daily).

**Comment by Macjutsu** [comment]
First, it's important to recognize that `softwareupdate` can fail to return a list and then a few minutes later work properly and return a list. So even if your Jamf EA shows success, that doesn't guarantee that `super` experienced the same success.

Second, do you have any super.logs actually showing a two hour timeout or a "fails immediately"? Because the default timeout is only two minutes, and with out any examples showing how `super` is "fails immediately" then I don't know have anything to go on.

**Comment by ecaya-hopper** [comment]
[super.log](https://github.com/Macjutsu/super/files/12526393/super.log)
Here is a recent example : you should see a timeout longer than expected in the last few lines of the log.

Softwareupdate check being unreliable is it's own issue i understand. We've just been confused as to why the timeout mechanism hasn't kicked in the logs.

**Comment by Macjutsu** [comment]
I resolved the zero day resetting issue: https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta4
