### ISSUE TITLE
Sending JAMF API credentials in "Files and Processes" exposes API credentials to client devices

### ISSUE THREAD

**Issue by Luke-From-IT** [Macjutsu/super#14]
Although the JAMF API credentials are saved to the keychain anyway, the API credentials are exposed to the client devices when Files and Processes are run with `--jamf-account` and `--jamf-password`. when running `sudo jamf policy -v`

Is it possible to send through a script and using the `$4` and `$5` variables instead and setting the script to run "after", or will this cause issues?

**Comment by Macjutsu** [comment]
First, the fact that we have to save the API credentials to the System Keychain is the fundamental security problem here. Any local admin can simply view the saved API credentials at any time without knowing anything about the command line or Jamf. Please consider upvoting this [Jamf feature request](https://ideas.jamf.com/ideas/JN-I-22444) as a permanent solution to this problem.

That being said, you could certainly use an "after" script to start `super` instead of Files and Processes. I was just trying to keep the initial documentation short and simple. I'll consider this workflow for the eventual `super` wiki.

**Comment by Macjutsu** [comment]
After much consideration and coding... `super` v2 will directly accept Jamf Parameters, so you won't have to use any intermediate script or Execute Command anymore.

**Comment by Macjutsu** [comment]
Check out `super` [v2.0-b1](https://github.com/Macjutsu/super/releases/tag/v2.0-b1).

Now supports Jamf Pro Policy script Parameters.
