### ISSUE TITLE
Installing with --auth-jamf-client and --auth-mdm-failover-to-user=ALWAYS Fails

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#140]
Situation: 

Applying config profile
<key>AuthMDMFailoverToUser</key>
<string>ALWAYS</string>

Installing with options below
--auth-jamf-client=any incorrect value
--auth-jamf-secret=any incorrect value

Returns a failed install, even when using the below to attempt to bypass the MDM auth fail as an installation parameter...
--auth-mdm-failover-to-user=ALWAYS

The goal was my attempt to forcefully causing an MDM failover to user to check its working...

**Comment by Macjutsu** [comment]
This is the expected behavior.

During `super` installation any errors are reported back to the Jamf log so you can identify installation problems. Most commonly you may have miss-typed the credentials. In this case, in order for the Jamf policy to recognize the error, `super` must exit and report the error.

Thus, failover only becomes active after `super` installation is complete.

I understand the desire to test failover, but the appropriate method would be to get `super` installed properly and then disable the network or rotate the Jamf API secret and run `super` again.
