### ISSUE TITLE
Feature Request: Super release checksums.txt add to releases

### ISSUE THREAD

**Issue by iancd-hofy** [Macjutsu/super#184]
Feature request: You currently kindly provide the release SHA256 hashes within the releases > version notes. Would it be possible to include hashes formally as a local checksum file with each release?  There's a Github Action that can automate this here.<https://github.com/marketplace/actions/generate-checksum>

This would enable automated checks of the super release download file downloaded with curl without having to scrape the release page.

**Comment by Macjutsu** [comment]
Good idea... if not v5.0.0-beta2 then by -beta3

**Comment by Macjutsu** [comment]
Downloading the entire `super` archive isn't very efficient given that it has a bunch of documentation (including screenshots) that is not necessary for deployment of `super`. As, such, really only `super` itself needs a checksum. Also, because I already add the checksum to the changelog, it literally takes no longer for the command to also spit out the checksum to a file... no need for me to learn how to implement GitHub Actions (which look neat, but with no prior knowledge, it would take me personally much longer to implement.)

Thus I'll be including [this SHA256 checksum file](https://github.com/Macjutsu/super/blob/5.0.0-beta2/super.checksum.txt) in all future builds.
