### ISSUE TITLE
Defer issue when lid is closed.

### ISSUE THREAD

**Issue by Tanti0007** [Macjutsu/super#187]
how can i get around when the user defers an update and closes the lid... next day user comes back and all deadline counts are reset and workflow begins again in 360 mins by default . they can dodge an update by just closing the lid and coming back to it. the workflow will just reset all deadlines and it will re-try in 6 hours. Have i missed an option ? using v4.0.3 super

Looks like super is trying to update while the lid is closed, finds no SU due to no network connectivity and resets all counters  inc defer counts.

This was also discussed in macadmins under here - 

https://macadmins.slack.com/archives/C03LKQ8EN2C/p1702327148122519

**Comment by Macjutsu** [comment]
Interesting... the system isn't supposed to allow third-party LaunchDaemons to run when the computer is locked.

There is no feature/option in `super` because it's not supposed to run when the computer is locked.

**Comment by Tanti0007** [comment]
Any suggestions on how to get around it ?

**Comment by dansutt** [comment]
I am seeing the same issue. I have the Super Status EA set up in Jamf and have this report from one the machines we are testing on.

Super status: Wed Feb 21 22:53:07: Inactive: Full super workflow complete! Automatic relaunch is disabled.

This user went home and closed the lid at about 17:00. Digging through some logs, this machine rebooted at 17:43 I am assuming because the notifications timed out and super tried to update/reboot? He is on an intel machine. Then It appears super tried to run ~5 hours later and stated it completed but the machine was never updated.

**Comment by Macjutsu** [comment]
Please try the latest release of `super` as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
