### ISSUE TITLE
Jamf Connect Login Screen Not Launching After Update

### ISSUE THREAD

**Issue by MonitorZero** [Macjutsu/super#195]
We utilize Jamf Connect as an SSO solution.

Everything works except when the user initiates the update by clicking "Restart" from the Superman dialog box. The system will update but once it gets back to the login screen it is the default local login screen and not the Jamf Connect SSO login screen.

The local login does work and once the user logs in and logs back out the Jamf Connect login screen is present but I believe this will trip some users and make them think they did something wrong.

Hardware: MacBook Air M1, 2020
OS Version: 13.X -> 13.6.1
Jamf Connect Version: 2.27
Superman Version: 4.0.3

Edit: Superman version 4.0.0 -> 4.0.3

**Comment by jhogan-uf** [comment]
I'm not familiar with Jamf Connect, but we use NoMAD and to our understanding that's the expected behavior for M-series MacBooks with FileVault enabled.

**Comment by iDrewbs** [comment]
This should be expected behavior. If you reboot afterwards and the Jamf connect login screen appears, everything’s fine. There are some updates/upgrades that will replace the login auto db which disables the Jamf connect login screen so it needs to be re-enabled for those cases. It helps to have a LaunchDaemon deployed that checks on startup if it’s enabled and will enable it if it’s not. On Jan 30, 2024, at 9:24 AM, MonitorZero ***@***.***> wrote:﻿
We utilize Jamf Connect as an SSO solution.
Everything works except when the user initiates the update by clicking "Restart" from the Superman dialog box. The system will update but once it gets back to the login screen it is the default local login screen and not the Jamf Connect SSO login screen.
The local login does work and once the user logs in and logs back out the Jamf Connect login screen is present but I believe this will trip some users and make them think they did something wrong.
Hardware: MacBook Air M1, 2020
OS Version: 13.X -> 13.6.1
Jamf Connect Version: 2.27
Superman Version: 4.0.0

**Comment by hannesgnad** [comment]
https://learn.jamf.com/bundle/jamf-connect-documentation-current/page/Re-enabling_the_Login_Window_after_a_Major_macOS_Upgrade.html

**Comment by Macjutsu** [comment]
Closing as this is not an issue with `super`.
