### ISSUE TITLE
password within plain text log

### ISSUE THREAD

**Issue by Shamus7878** [Macjutsu/super#210]
using saved passwords has anyone else seen plain test passwords displayed?
I run in verbose mode and every log I have checked so far has the users password. needless to say I have removed this feature for now.  ( Verbose Mode: Function manage_authentication_options: auth_user_password_keychain: ) LUCKYDUCK1234!!

**Comment by Macjutsu** [comment]
Yes... this is by design. https://github.com/Macjutsu/super/wiki/Troubleshooting#use-super-verbose-mode

"Further, when super is run with the --verbose-mode option, update credential passwords are also displayed in the command line but are not be saved to the super.log file on disk. This obviously helps identify password-related issues."
