### ISSUE TITLE
Ignore updates for a period of time

### ISSUE THREAD

**Issue by NoahTheFounder** [Macjutsu/super#23]
Hi,

I'm currently implementing your solution and wondered if there was any way to delay the start of the notification by a certain number of days automatically

What I mean by that is I would like to have super doing a recheck-defer every day but as soon as it detect a new update it sets the zero day date a week after the updates releases

The Idea would be to leave us enough time to test the update and verify the impact on users before deploying

For now we are doing a simple workaround where we republish a policy running once per users once we release the update to the users

Thanks for the great work on the project

**Comment by Macjutsu** [comment]
Two things, yes this is a planned feature for a future release.

However, you can already accomplish this behavior now with a deferred software update config profile. https://support.apple.com/guide/deployment/manage-software-updates-depc4c80847a

**Comment by NoahTheFounder** [comment]
Thanks a lot for the tip I'll check it out

**Comment by mikedowler** [comment]
+1 to this Feature Request.  

The deferred update config profile doesn't help in my situation, since I want to give users the opportunity to install the update themselves - I'd like the update to be visible, but just delay the `super` reminders.  The goal is to allow users to feel in control of when they update, so that they can avoid being reminded by just updating early.

Not to be too demanding, but it would be really great if this could be configured separately for major and minor upgrades/updates!  So, for example, if a minor update is released, the users get reminded immediately to install within 7 days.  When a major upgrade comes out, there is a grace period of 14 days where they can install if they want to, but won't get reminders.  After that 14 days is up, they start getting reminders to install within the next 7 days.

Thanks so much for your hard work on this, and for sharing with the community!

**Comment by Macjutsu** [comment]
The best way to handle this is via a [macOS deferral restrictions configuration profile](https://support.apple.com/guide/deployment/test-and-defer-software-updates-depd30715cbb). This is because the config profile will also prevent the native macOS user interface from showing updates and upgrades. Finally the newest versions of `super` have full support for this method.. https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1
