### ISSUE TITLE
Enhancement request: Final GUI user check before non-GUI restart triggered

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#242]
I've run into this case a few times this week: SUPER initially starts its workflow with no GUI user logged in, a user logs in during the middle of the workflow, and then the system reboots to install the update without any dialogs or notifications.
I had an idea that if SUPER is going through the "No GUI user" workflow, it could do one last check right before the reboot to see if a user is now logged in. If so, it could either restart under the GUI workflow and display dialogs or exit clean with a deferral to re-run later.

**Comment by Macjutsu** [comment]
For most workflows this is not possible due to the fact that `softwareupdate` can not reliably "only download" an update/upgrade if there is no logged in user.

As such, if there is no user logged into the system, `super` sends the "install now" command because it's the only method that is reliable if there is no logged in user. In other words, it's not possible to "stop" the update even if `super` noticed that the user had signed in.
