### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by giantwombat** [Macjutsu/super#39]
There seem to be a lot of security issues with this script, mainly race conditions where temporary files are used e.g. 

`curl "URL/" -L -o "/tmp/erase-install.pkg"`

It'd be better to do something like:

`output=$(mktemp)
curl "URL/" -L -o "${output}"`

**Comment by paragonsec** [comment]
Since this is still open thought I would add what other issues I see since they relate to the issue flagged by giantwombat.

On the function getIbmNotifier on line 2405 the IBM.Notifier.zip file is downloaded to /tmp. It would be possible to symlink that location to a root owned file which would cause IBM.Notifier.zip to overwrite a potentially critical root file.

https://github.com/Macjutsu/super/blob/b6ef6bcd76428b28fe7798d1c610a6df612aea7d/super#L2405

On the same function, on line 2412 a rm -Rf on the tmp file. This could also be used to symlink and delete arbitrary directories and files causing a denial of service.

https://github.com/Macjutsu/super/blob/b6ef6bcd76428b28fe7798d1c610a6df612aea7d/super#L2412

The issue with getEraseInstall is mostly the same. 

https://github.com/Macjutsu/super/blob/b6ef6bcd76428b28fe7798d1c610a6df612aea7d/super#L2443
https://github.com/Macjutsu/super/blob/b6ef6bcd76428b28fe7798d1c610a6df612aea7d/super#L2448

One exception is that on line 2445 you run the package through installer. This could be abused to privilege escalate to root by a user doing the following:

1. Downloading a sample of that package as well as write a blank /tmp/erase-install.pkg file so you control the permissions as the low level user
2. Using pkgutil to expand the package and gain access to the postinstall bash script
3. Backdoor the postinstall bash script with code that will be executed by root and repackage using pkgutil
4. Run the JAMF policy that executes the super script and watch for the root process to start. Once it does kill your internet connection to prevent the curl statement from overwriting your file
5. Copy your backdoored pkg to /tmp/erase-install.pkg where the script expects it to be

Once root runs installer the code you placed within the post install script will execute.

These issues could be fixed by doing something like:

```
tempDir=$(/usr/bin/mktemp -d "/tmp/super.XXXXXX")
cd "$tempDir"
/usr/bin/curl --location --silent "$eraseInstallURL" -o erase-install.pkg
```

That would make it impossible for a low-level user to gain access to the temporary directory that root created due to the randomness of the XXXX in mktemp. Then you could keep the rm -Rf and the installer the same.

**Comment by Macjutsu** [comment]
Thanks for this!

Funny timing, you actually confirmed the code I've already completed while working on the next build of `super`.

I'm also changing the `umask` and using `rm` after as well to further harden the dependencies installation code.

**Comment by paragonsec** [comment]
Awesome. Glad I can be of help. Looking forward to seeing the changes.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
