### ISSUE TITLE
Message Enhancement Request

### ISSUE THREAD

**Issue by DarthMJH** [Macjutsu/super#59]
Very minor one, In the message 'The deferrment deadline of xxxxx has passed'.  Deferrment should be spelt with 1 r, so 'deferment'

and something so minor I am embarrassed to mention it.  Is it possible not to have the full stops after each text line, I don't think they are required.  If not it is not a problem.

For the 'This computer will automatically restart very soon' is it possible to have a countdown timer displayed.  I see that a countdown timer is possible, as you have one in the deferral message 'Please make a selection in 00:00:54'
It just means the person knows exactly when the host will reboot as 'restart very soon' can be interpreted differently by different people.

Many thanks and love the product by the way

**Comment by Macjutsu** [comment]
1. Typo will be fixed in next beta probably out later today... good timing... also I usually do a spelling pass in the RC releases.
3. It is possible to change the text... simply edit the parameter strings in the `setDisplayLanguage()` function. As such, I don't plan on changing the current defaults because they work. You'll find that messing with the dialog boxes (even +/- something like a new-line) are fraught with drawing issues in JamfHelper and IBM Notifier. Future versions of `super` will be re-written to leverage SwiftDialog, but for now we have to deal with the drawing issues in JamfHelper and IBM Notifier.
4. Just because a dialog box can have a timer doesn't mean it's possible to know what to put in that timer. The selection timer is generated via something knowable... specifically the user input `--display-redraw=seconds` option. On the other hand, knowing in advance when the system will actually restart is literally impossible. There is nothing in macOS that will give us any concrete estimate of how long that restart takes. That dialog appears when `super` detects in the installation logs that "restart is soon"... sometimes that's 10 seconds before... sometimes it's 10 minutes. This is yet another way that the software update process leaves much to be desired.
