### ISSUE TITLE
Download and upgrade not working with workflow user (v3.0b6)

### ISSUE THREAD

**Issue by hcbraun** [Macjutsu/super#60]
Configuration is done via Managed Preferences. The workflow is set to user. The goal is to nudge users into clicking the update in the System Preferences.
Running v3.06b on Monterey 12.6.2, the background process is not downloading the Ventura update. When agreeing to update, the second super window is trying to open the none existing installer instead of opening the System Preferences.  

 Let me know if I can do anything to debug this further.

**Comment by Macjutsu** [comment]
As always, troubleshooting starts with reading the super.log.

**Comment by hcbraun** [comment]
Here is the verbose [super.log](https://github.com/Macjutsu/super/files/10369388/super.log). I can't see any obvious error

**Comment by Macjutsu** [comment]
The good news is that because you're on macOS 12.3 or newer `super` is correctly downloading the upgrade via `softwareupdate` and NOT the installer. You don't need the installer on 12.3 or newer to upgrade.

The bad news is that the rest of the user workflow is not working correctly here. At this point `super` should be prompting you to click the "Upgrade Now" button in the Software Update preference. I'll work on this for the next beta.

**Comment by hcbraun** [comment]
Awesome, thank you! Let me know if there is anything I can test on the 12.6.2 machine.

**Comment by Macjutsu** [comment]
Please test with the latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b7

**Comment by Macjutsu** [comment]
This issue should be resolved in the latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b8
