### ISSUE TITLE
Issues with s.u.p.e.r deployment through jamf. 

### ISSUE THREAD

**Issue by IhateMACOS** [Macjutsu/super#89]
Hey there, I have a weird issue with super where it works flawless on some of our devices and is not unable to update others. The error messages I'm getting are "No available recommended (non-system) update(s) or they may be deferred via configuration profile." "Error: Installation of macOS update/upgrade timed out after 300 seconds, trying again in 3600 seconds.". and a few others. I'm happy to send logs from user devices and screenshots of my Jamf Configuration profiles and policies. Thank you.

**Comment by Macjutsu** [comment]
The macOS update process is messy but these aren't issues directly caused by `super`. Both of these messages are `super` reacting to the macOS `softwareupdate` mechanism. In the first case, the system isn't finding any updates, in the second case the system update is stalling. For both of these, generally, the only thing you or `super` can do is to try again later. You can provide logs, but it's likely that if you simply restart these systems and try again, you will get different results.

**Comment by IhateMACOS** [comment]
I agree with you that macOS updates are an uphill battle, thank you for making the process easier for us admins. Cheers for the advice!
