### ISSUE TITLE
Send the Jamf Pro API command via MDM.

### ISSUE THREAD

**Issue by mauriciope** [Macjutsu/super#9]
Hello just start looking at your solution, looks really good.
I've noticed the in the Jamf MDM commands you did not specify the version.
For example:
`jamfJSON='{ "deviceIds": ["'${jamfProID}'"], "skipVersionVerification": false, "applyMajorUpdate": false, "updateAction": "DOWNLOAD_ONLY" }'`

The Jamf 10.38.1 API has this schema

```
{
  "deviceIds": [
    "1",
  ],
  "maxDeferrals": 7,
  "version": "12.0.1",
  "skipVersionVerification": false,
  "applyMajorUpdate": false,
  "updateAction": "DOWNLOAD_AND_INSTALL",
  "forceRestart": false
}

```
By ignoring the version you are requesting the latest available?
Regards

**Comment by Macjutsu** [comment]
Indeed, per [Jamf's documentation](https://developer.jamf.com/jamf-pro/reference/post_v1-macos-managed-software-updates-send-updates) "no version" is the same as asking for the "latest available". However, I'm also specifying `"applyMajorUpdate": false`, which will prevent a major macOS upgrade.

I do plan to support major upgrades in a future version.

**Comment by mauriciope** [comment]
Hello, our Apple Rep mentioned that  for upgrades their MDM call will treat it as Download and Install, even if the request is Download only.
We have a testing plan and we would like to target the latest updates to our testers and hold off the rest (or target the approved version) until their testing is completed.

**Comment by Macjutsu** [comment]
I'm not sure what the Apple Rep is talking about, at least via the Jamf API, because "download only" MDM command does work. In this case, system will download and prepare, but it will not restart to complete the installation. This is what allows `super` to ask the user if they want to defer the restart. After a deadline has passed or the user selects "restart", then `super` will send the "install and restart" MDM command. However, this is only reliable on macOS 11.5 or later. Thus, the minimum requirement for `super` to use the MDM update command is macOS 11.5 or later. 

As for targeting a specific older update version, the problem is that this is not possible with the `softwareupdate` command or reliable via the MDM command on macOS versions prior to 11.5. At this point I want to keep `super` feature parity between older systems (which can only use the `softwareupdate` command) and newer systems. **However, I will consider this for a future version of `super`, but again it will only be possible when updating via MDM command and if the system is already on macOS 11.5 or later.**

For now, the `super` workflow will adhere to the deferred update settings in a [Restriction Config Profile](https://support.apple.com/guide/deployment/manage-software-updates-depc4c80847a). Although this doesn't allow you to defer a specific version (thanks again Apple!), it does allow you defer the latest update for a number of days. You can use this against your "non-test" production systems to prevent `super` from updating to the latest version.

**Comment by mauriciope** [comment]
ok
