### ISSUE TITLE
Don't Understand why you write then delete these values from the plist

### ISSUE THREAD

**Issue by gzilla13** [Macjutsu/super#94]
Under the function
checkMacOSUpgrades() 

You have this snippet of code where you write two values to the super plist then immediately delete them

if [[ "$macOSUpgradeAVAILABLE" == "TRUE" ]]; then
	# Save macOS upgrade information for cache.
	if [[ $macOSVERSION -ge 1203 ]]; then  # Newer systems upgrade via softwareupdate.
		_**defaults write "$superPLIST" macOSSoftwareUpgradeLabel -string "$macOSSoftwareUpgradeLABEL"
		defaults write "$superPLIST" macOSSoftwareUpgradeTitle -string "$macOSSoftwareUpgradeTITLE"**_
		defaults delete "$superPLIST" macOSUpgradeName 2> /dev/null
		defaults delete "$superPLIST" macOSUpgradeVersion 2> /dev/null
	fi
	defaults write "$superPLIST" macOSUpgradeName -string "$macOSUpgradeNAME"
	[[ $macOSVERSION -ge 1015 ]] && defaults write "$superPLIST" macOSUpgradeVersion -string "$macOSUpgradeVERSION"
	_**defaults delete "$superPLIST" macOSSoftwareUpgradeLabel 2> /dev/null
	defaults delete "$superPLIST" macOSSoftwareUpgradeTitle 2> /dev/null**_

**Comment by Macjutsu** [comment]
That makes two of us...

I have no idea why any of those `defaults delete` statements are there... including the other's you didn't highlight. Leftovers from some earlier workflow logic perhaps?

Those items only affect the cache mechanism which will refresh automatically if it's been more than six hours since the last full check... so that's probably why this wasn't caught earlier.

I've removed the statements and are testing.

Good catch!

**Comment by Macjutsu** [comment]
Removed in latest release https://github.com/Macjutsu/super/releases/tag/v3.0-RC2
